config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :articles
  resources :users, except: [:new]
  get 'signup', to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 35}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    validates :username, presence: true,
                         uniqueness: { case_sensitive: false}, 
                         length: {minimum:3, maximum: 25}
    VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false}, 
                      length: {maximum: 105},
                      format: { with: VALID_EMAIL_REGEX }

    has_many :articles
    has_secure_password

    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def show
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(articles_params)
        @article.user_id = User.first
        if @article.save
            flash[:notice] = "Article was successfully created."
            redirect_to @article        
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @article.update(articles_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        if @article.destroy
            redirect_to articles_path
        end
    end

    private
    
    def set_article
        @article = Article.find(params[:id])
    end

    def articles_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :delete, :update, :show]

    def index
        @users = User.all
    end

    def show
    end

    def edit
    end

    def update
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome #{@user.username} to the Alpha Blog, you have successfully signup"
            redirect_to root_path
        else
            render 'new'
        end
    end

    def delete
        @user.destroy
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-md-center mt-4">
        <div class="col-8">
            <%= render 'shared/errors' , obj: @article %>
            <%= form_with(model: @article, local: true) do |f| %>
                <form>
                    <div class="card shadow mb-5 bg-white rounded">
                        <div class="card-body">
                            <div class="form-group">
                                <%= f.label :title, class: "col-form-label" %>
                                <%= f.text_field :title, class:"form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :description, class: "col-form-label" %>
                                <%= f.text_area :description, class:"form-control" %>
                            </div>
                            <%= f.submit class:"btn btn-primary"%>
                        </div>
                    </div>
                </form>
            <% end %>
        </div>
    </div>
</div>

<%= link_to "Back to All", articles_path, class:"btn btn-secondary ml-2" %>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4"> Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4"> Articles Listing Page</h1>
<div class="row justify-content-md-center">
    <div class="col-2">
        <%= link_to "Create New", new_article_path, class:"btn btn-primary justify-content-md-center" %>
    </div>
</div>
<br>
<% @articles.each do |article| %>
    <div class="row justify-content-md-center">
        <div class="col-8">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    by <%= article.user.username if article.user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
                    <p class="card-text"><%= truncate(article.description, length: 50) %></p>
                    <%= link_to "Show", article_path(article), class:"btn btn-primary" %>
                    <%= link_to "Edit", edit_article_path(article), class:"btn btn-info" %>
                    <%= link_to "Delete", article_path(article), method: :delete, class:"btn btn-danger" %>
                </div>
                <div class="card-footer text-muted">
                    Created: <%= time_ago_in_words(article.created_at) %> ago
                </div>
            </div>
        </div>
    </div>
    <br>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row justify-content-md-center mt-4">
    <div class="col-8">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                by <%= @article.user.username.capitalize if @article.user %>
            </div>
            <div class="card-body">
                <h5 class="card-title">Title: <%= @article.title %></h5>
                <p class="card-text text-left">Content: <%= simple_format(truncate(@article.description), length: 100, class: "text-left") %></p>
                <%= link_to "Edit", edit_article_path(@article), class:"btn btn-info shadow" %>
                <%= link_to "Delete", article_path(@article), method: :delete, class:"btn btn-danger shadow" %>
            </div>
            <div class="card-footer text-muted">
                Created: <%= time_ago_in_words(@article.created_at) %> ago
            </div>
        </div>
    </div>
</div>

<%= link_to "Back to All", articles_path, class:"btn btn-secondary ml-2" %>

app/views/home/index.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-4">
    <div class="col-8">
      <div class="jumbotron">
        <h1 class="display-4">Welcome to Alpha Blog</h1>
        <p class="lead">Here you can read and create articles, feel free to upload as many as you want.</p>
        <hr class="my-4">
        <p>You only need an account, so why dont we create one? click in the button below to start.</p>
        <p class="lead">
          <%= link_to "Sign Up", signup_path, class:"btn btn-primary btn-lg"  %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark">AlphaBlog.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <li><%= msg %></li>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="http://localhost:3000/articles">Alpha Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="http://localhost:3000/articles">List<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://localhost:3000/articles/new">New</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class %> from being saved</h4>
        <% obj.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger" role="alert">
                <li><%= msg %></li>
            </div>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-md-center mt-4">
        <div class="col-8">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with(model: @user, local: true) do |f| %>
                <form>
                    <div class="card shadow mb-5 bg-white rounded">
                        <div class="card-body">
                            <div class="form-group">
                                <%= f.label :username, class: "col-form-label" %>
                                <%= f.text_field :username, class:"form-control", placeholder: "Enter your user name" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :email, class: "col-form-label" %>
                                <%= f.email_field :email, class:"form-control", placeholder: "Enter your email" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :password, 'Password', class: "col-form-label" %>
                                <%= f.password_field :password, class:"form-control", placeholder: "Choose your password" %>
                            </div>
                            <%= f.submit(@user.new_record? ? "Sign up": "Update User", class:"btn btn-primary") %>
                        </div>
                    </div>
                </form>
            <% end %>
        </div>
    </div>
</div>

<%= link_to "Back to Articles", articles_path, class:"btn btn-secondary ml-2" %>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"> Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/new.html.erb
<h1 class="text-center mt-4">User Signup</h1>
<%= render 'form' %>